[package]
name = "kinesis_layout"
version = "0.1.0"
authors = ["Michael Thomas <Michaelt293@gmail.com>"]

[dependencies]
either = "1.5"
maplit = "1.0.1"

[[bin]]
bench = false
path = "src/main.rs"
name = "kinesis"
