[package]
name = "kinesis_layout"
edition = "2018"
version = "0.1.0"
authors = ["Michael Thomas <Michaelt293@gmail.com>"]

[dependencies]
either = "1.5"
maplit = "1.0.1"

[dev-dependencies]
indoc = "0.3"